sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t laurenzgamper/chrome-print .
  - docker run -d -p 127.0.0.1:8888:8888 laurenzgamper/chrome-print
  - docker ps -a

script:
  - docker ps -a
  - cd test && ./test.sh
